name: maven Github Actions
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    test:
        name: Run test for maven
        runs-on: ubuntu-latest
        steps:
            - name: get source code
              uses: actions/checkout@v6
            - name: set up JDK 17
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: running maven test
              run: mvn test
    build:
        needs: test
        name: building maven
        runs-on: ubuntu-latest
        outputs:
            artifact_data: ${{ steps.artifact_name.outputs.artifact_data }}
        steps:
            - name: get source code
              uses: actions/checkout@v6
            - name: set up JDK 17
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: building jar file
              run: mvn clean package
            - name: upload jar file
              uses: actions/upload-artifact@v6
              with:
                name: my-app-jar
                path: target/*.jar
            - name: Get the name of the output file
              id: artifact_name
              run: find target/*.jar -type f -execdir echo 'artifact_data={}' >> $GITHUB_OUTPUT ';'
    deploy:
        needs: build
        name: taking jar file and deploying
        runs-on: ubuntu-latest
        steps:
            - name: get artifacts data from build job
              uses: actions/download-artifact@v7
              with:
                name: my-app-jar
            - name: list my artifacts
              run: ls
            - name: getting artifact name from build job
              run: echo ${{ needs.build.outputs.artifact_data }}